




@dataclasses.dataclass
class TransferInfo:
    room: int           # 即 bootstrap room, mass level 的 request id.
    endpoint: str       # 代表 decode node 的 ip 地址.
    dst_port: int       # 代表 decode node 的 port 端口.
    mooncake_session_id: str  # 含义: d_node 在 MC_Trans_Engine 层面的唯一连接标识符，近似 node_id
    dst_kv_indices: npt.NDArray[np.int32]



"""
    decode: 启动时, decode node 向 prefill node 注册自己的 kvcache init addr 等信息.
    - KVArgsRegisterInfo 作为 decode node 发送给 prefill node 的初始化信息.
    - 使用 dataclasses 装饰器自动生成 __init__ 构造方法
"""
@dataclasses.dataclass
class KVArgsRegisterInfo:
    room: str
    endpoint: str            # 代表 decode node 的 ip 地址.
    dst_port: int            # 代表 decode node 的 port 端口.
    mooncake_session_id: str # 含义: d_node 在 MC_Trans_Engine 层面的唯一连接标识符，近似 node_id
    dst_kv_ptrs: list[int]
    dst_aux_ptrs: list[int]
    dst_tp_rank: int         # 含义: decode node 在起 attention tp_group 中的 rank
    dst_attn_tp_size: int    # 含义: decode node 在其 attention tp_group 中的 size
    dst_kv_item_len: int





# 创建一个指向目标内存地址的ctypes字节数组缓冲区
# 用于将接收到的数据写入到指定的内存位置
buffer = (ctypes.c_byte * len(data)).from_address(dst_addr)



    def init_engine(self):
        self.engine = MooncakeTransferEngine(
            hostname=self.local_ip, # gpu rank 进程自己找到的机器 ip <-> get_local_ip_auto()
            gpu_id=self.kv_args.gpu_id,
            ib_device=self.kv_args.ib_device,
        )

    """
    # for disagg
    def get_contiguous_buf_infos(self):
        # MLA has only one kv_buffer, so only the information of this buffer needs to be returned.
        #
        self.kv_buffer = [
            torch.zeros(
                    (size + page_size, 1, kv_lora_rank + qk_rope_head_dim),
                    dtype=self.store_dtype,
                    device=device)
                for _ in range(layer_num)
        ]

        self.data_ptrs = torch.tensor(
            [x.data_ptr() for x in self.kv_buffer],
            dtype=torch.uint64, device=self.device)

        kv_data_ptrs = [
            self.kv_buffer[i].data_ptr() for i in range(self.layer_num)]

        kv_data_lens = [
            self.kv_buffer[i].nbytes for i in range(self.layer_num)]

        kv_item_lens = [
            self.kv_buffer[i][0].nbytes * self.page_size for i in range(self.layer_num)]
    """
    def register_buffer_to_engine(self):
        # Batch register KV data buffers
        # 注册 每层 kv_cache 的起始地址、长度 bytes 信息.
        """
        kv_data_ptrs = [self.k_buffer[i].data_ptr() for i in range(self.layer_num)] +
                       [self.v_buffer[i].data_ptr() for i in range(self.layer_num)]

        kv_data_lens = [self._get_key_buffer(i).nbytes for i in range(self.layer_num)]+
                       [self._get_value_buffer(i).nbytes for i in range(self.layer_num)]
        """
        # 注册每一层的 kvcache 指针和 tensor_nbytes 信息.
        if self.kv_args.kv_data_ptrs and self.kv_args.kv_data_lens:
            self.engine.batch_register(
                #
                self.kv_args.kv_data_ptrs, self.kv_args.kv_data_lens
            )

        # Batch register auxiliary data buffers in metadata_buffers.
        # 注册 output_ids, output_hidden_states 等信息对应的指针和 tensor_nbytes 信息.
        if self.kv_args.aux_data_ptrs and self.kv_args.aux_data_lens:
            self.engine.batch_register(
                self.kv_args.aux_data_ptrs, self.kv_args.aux_data_lens
            )
